version: '3'
services:
    database:
        container_name: postgres
        image: postgres:11.1
        ports:
        - '5444:5432'
        volumes:
        - '${DB_DATA}:/var/lib/postgresql/data'
        environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWD}

    board.api:
        container_name: board.api
        image: board-api:latest
        build: .
        ports:
        - 8080:8080
        depends_on:
        - database
        links:
        - database
        volumes:
        - '${UPLOAD_DIR}:/upload'
        environment:
        - SERVER_PORT=8080
        - DATABASE_SERVER=postgres
        - DATABASE_PORT=5432
        - DATABASE_USER=${DB_USER}
        - DATABASE_PASSWD=${DB_PASSWD}